export const EgyptGovernments = [
    {id: '1', label: 'Cairo', value: 'Cairo'},
    {id: '2', label: 'Giza', value: 'Giza'},
    {id: '3', label: 'Alexandria', value: 'Alexandria'},
    {id: '4', label: 'Dakahlia', value: 'Dakahlia'},
    {id: '5', label: 'Red Sea', value: 'Red Sea'},
    {id: '6', label: 'Beheira', value: 'Beheira'},
    {id: '7', label: 'Fayoum', value: 'Fayoum'},
    {id: '8', label: 'Gharbiya', value: 'Gharbiya'},
    {id: '9', label: 'Ismailia', value: 'Ismailia'},
    {id: '10', label: 'Menofia', value: 'Menofia'},
    {id: '11', label: 'Minya', value: 'Minya'},
    {id: '12', label: 'Qaliubiya', value: 'Qaliubiya'},
    {id: '13', label: 'New Valley', value: 'New Valley'},
    {id: '14', label: 'Suez', value: 'Suez'},
    {id: '15', label: 'Aswan', value: 'Aswan'},
    {id: '16', label: 'Assiut', value: 'Assiut'},
    {id: '17', label: 'Beni Suef', value: 'Beni Suef'},
    {id: '18', label: 'Port Said', value: 'Port Said'},
    {id: '19', label: 'Damietta', value: 'Damietta'},
    {id: '20', label: 'Sharkia', value: 'Sharkia'},
    {id: '21', label: 'South Sinai', value: 'South Sinai'},
    {id: '22', label: 'Kafr Al sheikh', value: 'Kafr Al sheikh'},
    {id: '23', label: 'Matrouh', value: 'Matrouh'},
    {id: '24', label: 'Luxor', value: 'Luxor'},
    {id: '25', label: 'Qena', value: 'Qena'},
    {id: '26', label: 'North Sinai', value: 'North Sinai'},
    {id: '27', label: 'Sohag', value: 'Sohag'}
];
